#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 04:00:00
#SBATCH -J annotation_braker
#SBATCH --mail-type=ALL
#SBATCH --mail-user ellasj@hotmail.com

# Load modules
module load bioinfo-tools
module load braker/2.1.1_Perl5.24.1
module load augustus/3.2.3_Perl5.24.1
module load bamtools/2.5.1
module load blast/2.9.0+
module load GenomeThreader/1.7.0
module load samtools/1.8
module load GeneMark/4.62-es
module load diamond 
module load cdbfasta
module load perl_modules
module load biopython

# Your commands
# Ran in home:
# source $AUGUSTUS_CONFIG_COPY
# chmod a+w -R /home/ellasj/genome_analysis/Genomeanalysis-Batwings/augustus_config/species/
# cp -vf /sw/bioinfo/GeneMark/4.33-es/snowy/gm_key $HOME/.gm_key

export GENEMARK_PATH=/sw/bioinfo/GeneMark/4.62-es/snowy
braker.pl --species=M.Natalensis --genome=/home/ellasj/genome_analysis/Genomeanalysis-Batwings/data/additional_dna_assemble_data/sel3_NW_015504249.fna --bam=/home/ellasj/genome_analysis/Genomeanalysis-Batwings/code/alignment/Aligned.sortedByCoord.out.bam --AUGUSTUS_CONFIG_PATH=/home/ellasj/genome_analysis/Genomeanalysis-Batwings/augustus_config --AUGUSTUS_BIN_PATH=/sw/bioinfo/augustus/3.4.0/snowy/bin --AUGUSTUS_SCRIPTS_PATH=/sw/bioinfo/augustus/3.4.0/snowy/scripts --GENEMARK_PATH=/sw/bioinfo/GeneMark/4.62-es/snowy
