#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 02:00:00
#SBATCH -J Trimmomatic_RNA_ellasj
#SBATCH --mail-type=ALL
#SBATCH --mail-user ellasj@hotmail.com

# Load modules
module load bioinfo-tools
module load trimmomatic

# Commands
java -jar /sw/apps/bioinfo/trimmomatic/0.36/rackham/trimmomatic-0.36.jar PE /home/ellasj/genome_analysis/Genomeanalysis-Batwings/data/raw_data/sel3_SRR1719266.1.fastq.gz /home/ellasj/genome_analysis/Genomeanalysis-Batwings/data/raw_data/sel3_SRR1719266.2.fastq.gz lane1_forward_paired.fq.gz lane1_forward_unpaired.fq.gz lane1_reverse_paired.fq.gz lane1_reverse_unpaired.fq.gz ILLUMINACLIP:/sw/apps/bioinfo/trimmomatic/0.36/rackham/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
