#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 01:00:00
#SBATCH -J gff_to_fasta
#SBATCH --mail-type=ALL
#SBATCH --mail-user ellasj@hotmail.com

# Load modules
module load bioinfo-tools
module load cufflinks

# Commands
gffread -w scaff_3.fa -g /home/ellasj/genome_analysis/Genomeanalysis-Batwings/data/additional_dna_assemble_data/sel3_NW_015504249.fna \
/home/ellasj/genome_analysis/Genomeanalysis-Batwings/data/additional_annotation_data/extracted_scaff_3.gff

