#!/bin/bash -l
#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 02:00:00
#SBATCH -J alignment_ellasj
#SBATCH --mail-type=ALL
#SBATCH --mail-user ellasj@hotmail.com

# Load modules
module load bioinfo-tools
module load gcc star

# Your commands
STAR --runThreadN 2 --runMode genomeGenerate --genomeDir /home/ellasj/genome_analysis/Genomeanalysis-Batwings/results/alignment_results_reference_genome --genomeFastaFiles /home/ellasj/genome_analysis/Genomeanalysis-Batwings/data/additional_dna_assemble_data/sel3_NW_015504249.fna --genomeChrBinNbits 11 --genomeSAindexNbases 13

STAR --runThreadN 2 --genomeDir /home/ellasj/genome_analysis/Genomeanalysis-Batwings/results/alignment_results_reference_genome --readFilesCommand gunzip -c --readFilesIn /home/ellasj/genome_analysis/Genomeanalysis-Batwings/code/RNA_preprocessing_trimmomatic/lane1_forward_paired.fq.gz,/home/ellasj/genome_analysis/Genomeanalysis-Batwings/code/RNA_preprocessing_trimmomatic/lane1_forward_unpaired.fq.gz,/home/ellasj/genome_analysis/Genomeanalysis-Batwings/code/RNA_preprocessing_trimmomatic/lane1_reverse_paired.fq.gz,/home/ellasj/genome_analysis/Genomeanalysis-Batwings/code/RNA_preprocessing_trimmomatic/lane1_reverse_unpaired.fq.gz --outSAMtype BAM SortedByCoordinate
